@ECHO OFF

SET WEBDIR=#WEBDIR#\..\private
SET PHPDIRTS=#PHPDIRTS#
SET PHPDIRNTS=#PHPDIRNTS#

SET SVNDIR=#PHPDIRTS#\..\svn
SET PATH=%PATH%;%SVNDIR%

CD "%WEBDIR%"

IF EXIST "%WEBDIR%\composer.lock" ( DEL "%WEBDIR%\composer.lock" /F /Q )

"%PHPDIRTS%\php.exe" "%PHPDIRTS%\composer.phar" update --no-dev --prefer-dist
REM "%PHPDIRNTS%\php.exe" "%PHPDIRNTS%\composer.phar" update --no-dev --prefer-dist

ECHO.
ECHO Done

PAUSE