@ECHO OFF

SET WEBDIR=#WEBDIR#\..\private
SET PHPDIRTS=#PHPDIRTS#
SET PHPDIRNTS=#PHPDIRNTS#
SET VENDIR=#WEBDIR#\..\private\vendor
SET PHPUNITDIR=#WEBDIR#\..\private\vendor\phpunit\phpunit

SET PHP="%PHPDIRTS%\php.exe"
SET PHPUNIT="%PHPDIRTS%\phpunit.phar"

CD "%WEBDIR%"

ECHO Usage:
ECHO %%PHP%% %%PHPUNIT%% --bootstrap "%%VENDIR%%\monolog\monolog\tests\bootstrap.php" "%%VENDIR%%\monolog\monolog\tests\Monolog\Handler\MongoDBHandlerTest.php"
ECHO.

CMD