@ECHO OFF

REM Source: http://rubayathasan.com/tutorial/apache-ssl-on-windows/

SET BINDIR=#APACHEBINDIR#
SET OPENSSL=#APACHEBINDIR#\openssl.exe
SET CONFDIR=#CONFDIR#
REM SET OPENSSL_CONF=#CONFDIR#\openssl.cnf

CD %CONFDIR%

"%OPENSSL%" req -new -out "%CONFDIR%\server.csr"
"%OPENSSL%" rsa -in "%CONFDIR%\privkey.pem" -out "%CONFDIR%\server.key"
"%OPENSSL%" x509 -in "%CONFDIR%\server.csr" -out "%CONFDIR%\server.crt" -req -signkey "%CONFDIR%\server.key" -days 3650

ECHO Certificate created

PAUSE